# Generated by Django 4.2.7 on 2024-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_json', models.TextField(help_text='Строка с данными из запроса к API в виде строки json', verbose_name='Данные для конвертации')),
            ],
        ),
    ]
